const WRITE_SOURCES = Object.freeze([
  {
    source_file: 'src/main/api/httpClient.js',
    function_or_path: 'HttpClient.log(entry)',
    posture: 'primary runtime provider logging path',
    writes_through: 'EvidenceRepository.insertApiRequestLog',
    current_endpoint_posture: 'endpoint is persisted as supplied to HttpClient.json',
    current_error_text_posture: 'errorMessage is persisted as supplied by HttpClient error handling',
    provider_execution_affected_by_this_preview: false
  },
  {
    source_file: 'src/main/db/evidenceRepository.js',
    function_or_path: 'EvidenceRepository.insertApiRequestLog(log)',
    posture: 'single repository insert helper for api_request_logs rows',
    writes_through: 'prepared INSERT INTO api_request_logs',
    current_endpoint_posture: 'endpoint is stored without redaction/truncation in this helper',
    current_error_text_posture: 'error_message is stored without redaction/truncation in this helper',
    provider_execution_affected_by_this_preview: false
  },
  {
    source_file: 'src/main/workers/manualDiscoveryWorker.js',
    function_or_path: 'new HttpClient({ repository, runId }) -> ZKillDiscoveryClient',
    posture: 'provider-backed Discovery provenance',
    writes_through: 'HttpClient.log',
    current_endpoint_posture: 'inherits HttpClient endpoint persistence posture',
    current_error_text_posture: 'inherits HttpClient error_message persistence posture',
    provider_execution_affected_by_this_preview: false
  },
  {
    source_file: 'src/main/workers/manualExpansionWorker.js',
    function_or_path: 'new HttpClient({ repository, runId }) -> EsiClient',
    posture: 'ESI Evidence expansion provenance',
    writes_through: 'HttpClient.log',
    current_endpoint_posture: 'inherits HttpClient endpoint persistence posture',
    current_error_text_posture: 'inherits HttpClient error_message persistence posture',
    provider_execution_affected_by_this_preview: false
  },
  {
    source_file: 'src/main/workers/actorWatchCollector.js',
    function_or_path: 'new HttpClient({ repository, runId }) -> zKill/ESI clients',
    posture: 'Watch provider provenance',
    writes_through: 'HttpClient.log',
    current_endpoint_posture: 'inherits HttpClient endpoint persistence posture',
    current_error_text_posture: 'inherits HttpClient error_message persistence posture',
    provider_execution_affected_by_this_preview: false
  },
  {
    source_file: 'src/main/workers/systemRadiusCollector.js',
    function_or_path: 'new HttpClient({ repository, runId }) -> zKill/ESI clients',
    posture: 'system/radius Watch provider provenance',
    writes_through: 'HttpClient.log',
    current_endpoint_posture: 'inherits HttpClient endpoint persistence posture',
    current_error_text_posture: 'inherits HttpClient error_message persistence posture',
    provider_execution_affected_by_this_preview: false
  },
  {
    source_file: 'src/main/metadata/reportHydrator.js',
    function_or_path: 'new HttpClient({ repository, runId, runType: metadata }) -> EsiClient',
    posture: 'Hydration provider provenance; readability metadata only',
    writes_through: 'HttpClient.log',
    current_endpoint_posture: 'inherits HttpClient endpoint persistence posture',
    current_error_text_posture: 'inherits HttpClient error_message persistence posture',
    provider_execution_affected_by_this_preview: false
  },
  {
    source_file: 'scripts/* verification fixtures',
    function_or_path: 'fake clients and fixture helpers calling insertApiRequestLog',
    posture: 'test/fixture provenance rows',
    writes_through: 'EvidenceRepository.insertApiRequestLog',
    current_endpoint_posture: 'fixture endpoints are supplied directly by tests',
    current_error_text_posture: 'fixture error text is supplied directly by tests',
    provider_execution_affected_by_this_preview: false
  }
]);

const PERSISTED_FIELDS = Object.freeze([
  field('request_id', 'runtime provenance id', 'generated by caller/helper', 'not secret-bearing by design'),
  field('run_id', 'run provenance link', 'stored as supplied', 'support provenance only'),
  field('run_type', 'collection/metadata/unscoped lane', 'stored as supplied/defaulted', 'classification/provenance'),
  field('provider', 'provider label', 'stored as supplied', 'provider provenance'),
  field('endpoint', 'provider endpoint string', 'stored as supplied today', 'query values and secret-like values are not proven redacted before persistence'),
  field('method', 'HTTP method', 'stored as supplied', 'low sensitivity'),
  field('status_code', 'HTTP status', 'stored as supplied', 'low sensitivity'),
  field('duration_ms', 'timing', 'stored as supplied', 'low sensitivity'),
  field('cache_status', 'cache/retry posture', 'stored as supplied/defaulted', 'low sensitivity'),
  field('retry_count', 'retry count', 'stored as supplied/defaulted', 'low sensitivity'),
  field('rate_limited', 'provider wait signal', 'stored as supplied/defaulted', 'low sensitivity'),
  field('error_message', 'diagnostic free text', 'stored as supplied today', 'secret redaction and length bounds are not proven before persistence'),
  field('requested_at', 'timestamp', 'stored as supplied/defaulted', 'low sensitivity')
]);

function buildApiRequestLogRedactionReadinessPreview() {
  return {
    action: 'support.api_request_log_redaction_readiness.preview',
    classification: 'read-only api_request_logs redaction readiness proof',
    generated_at: new Date().toISOString(),
    read_only: true,
    mutates_state: false,
    renderer_payload_ignored: true,
    provider_calls: 0,
    zkill_calls: 0,
    esi_calls: 0,
    creates_support_artifacts: false,
    creates_logs: false,
    creates_exports: false,
    creates_files: false,
    creates_directories: false,
    api_request_log_writes: 0,
    evidence_writes: 0,
    discovery_ref_mutations: 0,
    hydration_writes: 0,
    assessment_writes: 0,
    watch_mutations: 0,
    storage_config_writes: 0,
    external_io_config_writes: 0,
    schema_changes: false,
    runtime_enforcement_active: false,
    command_blocking_active: false,
    log_write_behavior_changed: false,
    trace_pack_writer_changed: false,
    light_log_writer_created: false,
    policy_source: 'support.trace_log_redaction_policy.preview',
    table: {
      name: 'api_request_logs',
      role: 'provider provenance and operational diagnostics',
      is_evidence: false,
      is_discovery: false,
      is_hydration_output: false,
      is_assessment_memory: false,
      raw_provider_response_body_columns: [],
      raw_esi_payload_columns: [],
      persisted_fields: PERSISTED_FIELDS
    },
    write_sources: WRITE_SOURCES,
    current_posture: {
      endpoint_string: posture('unproven', 'Persisted endpoint is passed through from caller/HttpClient without centralized redaction or max-length enforcement.'),
      query_values: posture('absent', 'No persistence-layer query value stripping is currently applied to api_request_logs.endpoint.'),
      secret_token_auth_cookie_redaction: posture('unproven', 'No centralized pre-persistence redaction proof exists for endpoint or error_message.'),
      error_message_free_text: posture('unproven', 'error_message is persisted as supplied by HttpClient or direct repository callers.'),
      free_text_length_bounds: posture('absent', 'No max-length policy is enforced before api_request_logs persistence.'),
      provider_status_timing_cache_retry: posture('proven_present', 'provider, method, status_code, duration_ms, cache_status, retry_count, rate_limited, and requested_at are persisted as support provenance fields.'),
      raw_provider_response_bodies: posture('excluded_by_schema', 'api_request_logs has no response-body column and HttpClient.log does not pass response body text.'),
      raw_esi_payloads: posture('excluded_by_schema', 'api_request_logs has no raw ESI payload column; raw ESI evidence lives in killmails, not log rows.')
    },
    affected_surfaces: {
      trace_pack_assembly_redaction: 'separate_already_hardened_by_HS188',
      reports: 'read existing api_request_logs endpoint/error fields; this preview does not change report behavior',
      hydration: 'may write metadata run API provenance through HttpClient/fake clients; this preview does not change Hydration behavior',
      evidence: 'api_request_logs are not Evidence/EVEidence and this preview writes no Evidence/EVEidence',
      discovery: 'api_request_logs are not Discovery refs and this preview mutates no Discovery refs',
      provider_execution: 'not affected; no provider calls or HttpClient behavior changes',
      light_log_export: 'not created'
    },
    recommended_later_hardening: {
      smallest_insertion_point: 'centralize sanitization immediately before EvidenceRepository.insertApiRequestLog persists endpoint and error_message',
      preferred_files: [
        'src/main/db/evidenceRepository.js',
        'src/main/api/httpClient.js'
      ],
      rationale: [
        'EvidenceRepository.insertApiRequestLog is the single repository helper for persisted api_request_logs rows.',
        'HttpClient.log is the primary runtime provider path and already has provider/method/status/timing context.',
        'A later change can sanitize endpoint/error values before persistence without changing provider execution or report parsing semantics if route shape is preserved.'
      ],
      defer_until_accepted: [
        'query value stripping before persistence',
        'secret/token/auth/cookie redaction before persistence',
        'error_message max length before persistence',
        'report parsing compatibility review for endpoint route shape'
      ]
    },
    boundary: [
      'Read-only API request log redaction readiness preview only; it does not change api_request_logs write behavior.',
      'It does not change HttpClient, provider workers, trace-pack writer behavior, reports, Hydration, Evidence/EVEidence, Discovery refs, Watch, storage config, External I/O config, or schema.',
      'It does not call providers, create support artifacts, create light-log exports, activate runtime enforcement, or block commands.',
      'Persisted api_request_logs are provider provenance and operational diagnostics, not Evidence/EVEidence.',
      'Trace-pack assembly redaction from HS188 is separate from persisted api_request_logs redaction.'
    ]
  };
}

function field(name, meaning, currentPosture, sensitivity) {
  return {
    name,
    meaning,
    current_posture: currentPosture,
    sensitivity
  };
}

function posture(status, notes) {
  return {
    status,
    notes
  };
}

module.exports = {
  buildApiRequestLogRedactionReadinessPreview
};
