const WRITE_SOURCES = Object.freeze([
  {
    source_file: 'src/main/api/httpClient.js',
    function_or_path: 'HttpClient.log(entry)',
    posture: 'primary runtime provider logging path',
    writes_through: 'EvidenceRepository.insertApiRequestLog',
    current_endpoint_posture: 'provider request endpoint is passed unchanged to fetch, then sanitized at repository insert before persistence',
    current_error_text_posture: 'errorMessage is passed by HttpClient error handling, then sanitized at repository insert before persistence',
    provider_execution_affected_by_this_preview: false
  },
  {
    source_file: 'src/main/db/evidenceRepository.js',
    function_or_path: 'EvidenceRepository.insertApiRequestLog(log)',
    posture: 'single repository insert helper for api_request_logs rows',
    writes_through: 'prepared INSERT INTO api_request_logs',
    current_endpoint_posture: 'endpoint is query-value redacted, secret-like segment/assignment redacted, and length-bounded before INSERT',
    current_error_text_posture: 'error_message has URL query values, secret-like assignments, bearer/basic values, and length bounded before INSERT',
    provider_execution_affected_by_this_preview: false
  },
  {
    source_file: 'src/main/workers/manualDiscoveryWorker.js',
    function_or_path: 'new HttpClient({ repository, runId }) -> ZKillDiscoveryClient',
    posture: 'provider-backed Discovery provenance',
    writes_through: 'HttpClient.log',
    current_endpoint_posture: 'inherits HttpClient endpoint persistence posture',
    current_error_text_posture: 'inherits HttpClient error_message persistence posture',
    provider_execution_affected_by_this_preview: false
  },
  {
    source_file: 'src/main/workers/manualExpansionWorker.js',
    function_or_path: 'new HttpClient({ repository, runId }) -> EsiClient',
    posture: 'ESI Evidence expansion provenance',
    writes_through: 'HttpClient.log',
    current_endpoint_posture: 'inherits HttpClient endpoint persistence posture',
    current_error_text_posture: 'inherits HttpClient error_message persistence posture',
    provider_execution_affected_by_this_preview: false
  },
  {
    source_file: 'src/main/workers/actorWatchCollector.js',
    function_or_path: 'new HttpClient({ repository, runId }) -> zKill/ESI clients',
    posture: 'Watch provider provenance',
    writes_through: 'HttpClient.log',
    current_endpoint_posture: 'inherits HttpClient endpoint persistence posture',
    current_error_text_posture: 'inherits HttpClient error_message persistence posture',
    provider_execution_affected_by_this_preview: false
  },
  {
    source_file: 'src/main/workers/systemRadiusCollector.js',
    function_or_path: 'new HttpClient({ repository, runId }) -> zKill/ESI clients',
    posture: 'system/radius Watch provider provenance',
    writes_through: 'HttpClient.log',
    current_endpoint_posture: 'inherits HttpClient endpoint persistence posture',
    current_error_text_posture: 'inherits HttpClient error_message persistence posture',
    provider_execution_affected_by_this_preview: false
  },
  {
    source_file: 'src/main/metadata/reportHydrator.js',
    function_or_path: 'new HttpClient({ repository, runId, runType: metadata }) -> EsiClient',
    posture: 'Hydration provider provenance; readability metadata only',
    writes_through: 'HttpClient.log',
    current_endpoint_posture: 'inherits HttpClient endpoint persistence posture',
    current_error_text_posture: 'inherits HttpClient error_message persistence posture',
    provider_execution_affected_by_this_preview: false
  },
  {
    source_file: 'scripts/* verification fixtures',
    function_or_path: 'fake clients and fixture helpers calling insertApiRequestLog',
    posture: 'test/fixture provenance rows',
    writes_through: 'EvidenceRepository.insertApiRequestLog',
    current_endpoint_posture: 'fixture endpoints are supplied directly by tests',
    current_error_text_posture: 'fixture error text is supplied directly by tests',
    provider_execution_affected_by_this_preview: false
  }
]);

const PERSISTED_FIELDS = Object.freeze([
  field('request_id', 'runtime provenance id', 'generated by caller/helper', 'not secret-bearing by design'),
  field('run_id', 'run provenance link', 'stored as supplied', 'support provenance only'),
  field('run_type', 'collection/metadata/unscoped lane', 'stored as supplied/defaulted', 'classification/provenance'),
  field('provider', 'provider label', 'stored as supplied', 'provider provenance'),
  field('endpoint', 'provider endpoint string', 'sanitized at EvidenceRepository.insertApiRequestLog before INSERT', 'query values and secret-like values are redacted before persistence while route shape is preserved'),
  field('method', 'HTTP method', 'stored as supplied', 'low sensitivity'),
  field('status_code', 'HTTP status', 'stored as supplied', 'low sensitivity'),
  field('duration_ms', 'timing', 'stored as supplied', 'low sensitivity'),
  field('cache_status', 'cache/retry posture', 'stored as supplied/defaulted', 'low sensitivity'),
  field('retry_count', 'retry count', 'stored as supplied/defaulted', 'low sensitivity'),
  field('rate_limited', 'provider wait signal', 'stored as supplied/defaulted', 'low sensitivity'),
  field('error_message', 'diagnostic free text', 'sanitized at EvidenceRepository.insertApiRequestLog before INSERT', 'secret redaction, URL query redaction, and length bounds are applied before persistence'),
  field('requested_at', 'timestamp', 'stored as supplied/defaulted', 'low sensitivity')
]);

function buildApiRequestLogRedactionReadinessPreview() {
  return {
    action: 'support.api_request_log_redaction_readiness.preview',
    classification: 'read-only api_request_logs redaction readiness proof',
    generated_at: new Date().toISOString(),
    read_only: true,
    mutates_state: false,
    renderer_payload_ignored: true,
    provider_calls: 0,
    zkill_calls: 0,
    esi_calls: 0,
    creates_support_artifacts: false,
    creates_logs: false,
    creates_exports: false,
    creates_files: false,
    creates_directories: false,
    api_request_log_writes: 0,
    evidence_writes: 0,
    discovery_ref_mutations: 0,
    hydration_writes: 0,
    assessment_writes: 0,
    watch_mutations: 0,
    storage_config_writes: 0,
    external_io_config_writes: 0,
    schema_changes: false,
    runtime_enforcement_active: false,
    command_blocking_active: false,
    log_write_behavior_changed: false,
    persistence_sanitization_active: true,
    persistence_sanitization_scope: 'api_request_logs.endpoint and api_request_logs.error_message at EvidenceRepository.insertApiRequestLog',
    trace_pack_writer_changed: false,
    light_log_writer_created: false,
    policy_source: 'support.trace_log_redaction_policy.preview',
    table: {
      name: 'api_request_logs',
      role: 'provider provenance and operational diagnostics',
      is_evidence: false,
      is_discovery: false,
      is_hydration_output: false,
      is_assessment_memory: false,
      raw_provider_response_body_columns: [],
      raw_esi_payload_columns: [],
      persisted_fields: PERSISTED_FIELDS
    },
    write_sources: WRITE_SOURCES,
    current_posture: {
      endpoint_string: posture('proven_at_insert', 'EvidenceRepository.insertApiRequestLog sanitizes endpoint before INSERT while preserving route shape for diagnostics/report parsing.'),
      query_values: posture('proven_at_insert', 'Endpoint query keys are preserved with redacted values before persistence; URL query values inside error_message are redacted before persistence.'),
      secret_token_auth_cookie_redaction: posture('proven_for_tested_patterns', 'Secret/token/auth/cookie-like query/path/assignment and bearer/basic patterns are redacted before persistence for tested endpoint/error patterns.'),
      error_message_free_text: posture('proven_at_insert', 'error_message is sanitized for URL query values and secret-like text before INSERT.'),
      free_text_length_bounds: posture('proven_at_insert', 'endpoint and error_message are bounded before api_request_logs persistence.'),
      provider_status_timing_cache_retry: posture('proven_present', 'provider, method, status_code, duration_ms, cache_status, retry_count, rate_limited, and requested_at are persisted as support provenance fields.'),
      raw_provider_response_bodies: posture('excluded_by_schema', 'api_request_logs has no response-body column and HttpClient.log does not pass response body text.'),
      raw_esi_payloads: posture('excluded_by_schema', 'api_request_logs has no raw ESI payload column; raw ESI evidence lives in killmails, not log rows.')
    },
    affected_surfaces: {
      trace_pack_assembly_redaction: 'separate_already_hardened_by_HS188',
      reports: 'read existing api_request_logs endpoint/error fields; this preview does not change report behavior',
      hydration: 'may write metadata run API provenance through HttpClient/fake clients; this preview does not change Hydration behavior',
      evidence: 'api_request_logs are not Evidence/EVEidence and this preview writes no Evidence/EVEidence',
      discovery: 'api_request_logs are not Discovery refs and this preview mutates no Discovery refs',
      provider_execution: 'not affected; no provider calls or HttpClient behavior changes',
      light_log_export: 'not created'
    },
    recommended_later_hardening: {
      smallest_insertion_point: 'completed for api_request_logs.endpoint and api_request_logs.error_message at EvidenceRepository.insertApiRequestLog',
      preferred_files: [
        'src/main/db/evidenceRepository.js'
      ],
      rationale: [
        'EvidenceRepository.insertApiRequestLog is the single repository helper for persisted api_request_logs rows.',
        'Sanitizing at repository insert covers HttpClient.log and direct fixture/repository callers without changing provider execution.',
        'Route path segments remain intact so report parsing can continue to derive provider/system/actor/window context.'
      ],
      defer_until_accepted: [
        'any broader log framework/export work',
        'any light operational log writer/export',
        'any historical backfill of already-persisted api_request_logs rows'
      ]
    },
    boundary: [
      'API request log persistence sanitization is active only for api_request_logs.endpoint and api_request_logs.error_message at repository insert.',
      'It does not change provider request URLs, HttpClient fetch/retry/provider execution behavior, provider workers, trace-pack writer behavior, reports, Hydration, Evidence/EVEidence, Discovery refs, Watch, storage config, External I/O config, or schema.',
      'It does not call providers, create support artifacts, create light-log exports, activate runtime enforcement, or block commands.',
      'Persisted api_request_logs are provider provenance and operational diagnostics, not Evidence/EVEidence.',
      'Trace-pack assembly redaction from HS188 is separate from persisted api_request_logs redaction.'
    ]
  };
}

function field(name, meaning, currentPosture, sensitivity) {
  return {
    name,
    meaning,
    current_posture: currentPosture,
    sensitivity
  };
}

function posture(status, notes) {
  return {
    status,
    notes
  };
}

module.exports = {
  buildApiRequestLogRedactionReadinessPreview
};
